language: c

sudo: required
dist: bionic

matrix:
    include:
        -
            os: linux
            compiler: clang
        -
            os: linux
            compiler: gcc
        -
            os: linux
            compiler: gcc-8
            env:
                - CC=gcc-8 AR=gcc-ar-8 NM=gcc-nm-8 RANLIB=gcc-ranlib-8
                - NO_32BIT_TEST=1
        -
            os: linux
            compiler: gcc-9
            env:
                - CC=gcc-9 AR=gcc-ar-9 NM=gcc-nm-9 RANLIB=gcc-ranlib-9
                - NO_32BIT_TEST=1
        -
            os: linux
            compiler: gcc-10
            env:
                - CC=gcc-10 AR=gcc-ar-10 NM=gcc-nm-10 RANLIB=gcc-ranlib-10
                - NO_32BIT_TEST=1

addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - pkg-config
            - gcc-multilib
            - openssl
            - cppcheck
            - xmlto
            - docbook-utils
            - gcc-8
            - gcc-9
            - gcc-10

script:
    - autoreconf -i && OK_AUTOCONF=y
    - >
        [ "$OK_AUTOCONF" = y ] && ./configure \
            --enable-kcapi-hasher \
            --enable-kcapi-test \
            --enable-kcapi-rngapp \
            --enable-kcapi-encapp \
            --enable-kcapi-dgstapp \
            --enable-lib-asym \
            --enable-lib-kpp && OK_CONFIGURE=y
    - >
        [ "$OK_CONFIGURE" = y ] && make -j`nproc --all`
    - >
        [ "$OK_CONFIGURE" = y ] && make cppcheck
    - >
        [ "$OK_CONFIGURE" = y ] && make scan
    - >
        [ "$OK_CONFIGURE" = y ] && cd test && bash ./test-invocation.sh
